### PR TITLE
deps: fix libgit 1.1.0 compability

### LINKED ISSUE #5: need a new release for pygit2 1.4.0
👋  during libgit2 1.1.0 [upgrade PR](https://github.com/Homebrew/homebrew-core/pull/65706), we found that the new release is needed for literate-git, relevant error log

```
  In file included from src/blob.c:30:
  In file included from src/blob.h:34:
  src/types.h:36:2: error: You need a compatible libgit2 version (0.99.x or 1.0.x)
  #error You need a compatible libgit2 version (0.99.x or 1.0.x)
   ^
  1 error generated.
  error: command '/usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang' failed with exit code 1
  Building wheel for pygit2 (PEP 517): finished with status 'error'
  ERROR: Failed building wheel for pygit2
Failed to build pygit2
ERROR: Could not build wheels for pygit2 which use PEP 517 and cannot be installed directly
Exception information:
Traceback (most recent call last):
  File "/usr/local/Cellar/literate-git/0.3.1_5/libexec/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 228, in _main
    status = self.run(options, args)
  File "/usr/local/Cellar/literate-git/0.3.1_5/libexec/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 182, in wrapper
    return func(self, options, args)
  File "/usr/local/Cellar/literate-git/0.3.1_5/libexec/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 364, in run
    raise InstallationError(
pip._internal.exceptions.InstallationError: Could not build wheels for pygit2 which use PEP 517 and cannot be installed directly
Removed build tracker: '/private/tmp/pip-req-tracker-__xsh2z8'
```

---

also attach some relevant python_version requirements

```
pygit2<=0.28.2; python_version < '3.8'
pygit2>=1.2.0; python_version >= '3.8'
```

### PR DESCRIPTION
**Pull request by chenrui333**
closes #5

relates to https://github.com/Homebrew/homebrew-core/pull/65706

### CODE REVIEW

**Comment by bennorth** [comment]
Hi, thanks for the PR.  It would be good to move literate-git to the current `pygit2`, yes.  I'm fine with removing Python 3.5 support, since it became end-of-life a couple of months ago, but I'm reluctant to remove Python 3.6 and Python 3.7 from the Travis config.  I've made an [experimental branch `update-pygit2`](https://github.com/bennorth/literate-git/commits/update-pygit2) which removes the `venvgit2` requirement, as it seems that `pygit2` is now packaged in a way which doesn't require it.  This [successfully built](https://travis-ci.org/github/bennorth/literate-git/builds/746333762) and passed tests under the Travis `focal` image, for Pythons 3.6, 3.7, 3.8, and 3.9.

I'm not familiar with the details of how Homebrew operates, sorry, but might something like this work for you?  If so, I'll tidy it up and make a new release.

**Comment by aspiers** [comment]
Any idea how libgit2 gets provided in this Travis environment?  I can't see it mentioned in the build log you reference, so I'm guessing it's pre-included in the `focal` image, but not sure.  I see your build uses `sudo` rather than containers so there may be room for getting faster builds by switching to containers ... but then you might run into a vaguely similar challenge to what I had with https://github.com/aspiers/git-deps/issues/73.  See also the linked issue https://github.com/travis-ci/apt-package-safelist/issues/4285.

**Comment by bennorth** [comment]
@aspiers — `libgit2` arrives as part of the binary `pygit2` wheel.  From [its docs](https://www.pygit2.org/install.html): _Libgit2 v1.1.x; binary wheels already include libgit2, so you only need to worry about this if you install the source package_.

**Comment by aspiers** [comment]
Ahhh, thanks!  That sounds like some newer magic which maybe didn't exist a few years ago when I last looked at this.  Or maybe I just missed it.

**Comment by bennorth** [comment]
I've just pushed changes to `develop` (967caf47f2f16) which move to `pygit2>=1.4.0`, so I'm closing this.  Please re-open if this doesn't address your use-case with Homebrew.

**Pull request closed without merging**
